### PR TITLE
Kartik export

### PR DESCRIPTION
**Pull request by Kartikdot**
I have added the functionality to export to facebook for now. Please review it and i will then push changes to also export to instagram.

1. I have used facebook sdk to use the share option and it requires the app to be registered with a developer account on facebook. Currently i have used my account and added my computers hash key on the developer website. Please provide with an alternate account that we can use for development purposes.

2. For the app to work, a privacy policy url is required on the developer website for the app. Currently i have entered www.google.com. We need an actual privacy policy url having the privacy policy that will state that this app collects no personal data.

### CODE REVIEW

**Comment by madhavrathi** [comment]
@Kartik2016 For the privacy policy, can we host a webpage on gh pages ?
Please create a separate issue for that and proceed. I will merge this PR for now. Thanks for you PR.

**Comment by Kartikdot** [comment]
What is a gh page? Sorry i am not aware. Yes i'll open a new issue. Also the developer responsibility should be transferred as it is only linked to my account. Shall i create an issue for the same and make a new facebook account and set it up as a developer account. Then we can share its credentials and share with other developers who might wanna work with other features of FB sdk. I think this will also serve as an account for other apps of NWOC that need facebook sdk or api.

**Comment by Kartikdot** [comment]
Closes #4

**Comment by madhavrathi** [comment]
@Karthik2016 please go ahead and make an issue for that. Making a developer FB account sounds cool to me.

**Comment by Kartikdot** [comment]
Ok sure.

**Pull request merged**
