### PR TITLE
Solves Issue#1

### PR DESCRIPTION
**Pull request by AK-007**
Implemented ConstraintLayout in activity_main.xml.
Adjusted the Top and Bottom text to prevent them from cutting off.

### CODE REVIEW

**Comment by madhavrathi** [comment]
@AK-007 Thanks. It would be much appreciated if you post screenshots of the changes so that it is easier to track the changes.

**Comment by AK-007** [comment]
Please review and merge.
screenshot_2017-11-30-13-32-21-520_com example mdhvr memegenerator

**Review by madhavrathi — CHANGES_REQUESTED** [review]
The text is supposed to be on the image. Please fix this.

**Comment by AK-007** [comment]
screenshot_2017-11-30-14-30-09-337_com example mdhvr memegenerator

**Review by madhavrathi — APPROVED** [review]
Thanks. Please make sure that load picture button is added in future PR. Merging this for now. Great work !

**Pull request merged**
