### PR TITLE
Adding search functionality

### PR DESCRIPTION
**Pull request by ishita1818**
Now the user will be able to search within the app.

_here are the latest screenshots_

- 

screenshot_20171223-000703 1

- 
screenshot_20171223-000737 1

### CODE REVIEW

**Comment by ishita1818** [comment]
@madhavrathi review it please.

**Review by madhavrathi — APPROVED** [review]
@ishita1818 Thanks for PR.

**Comment by madhavrathi** [comment]
@ishita1818 Update README for this new feature. Cheers!

**Comment by ishita1818** [comment]
@madhavrathi  yup... okay.. will send a pr soon.

**Comment by ShikharJ** [comment]
@madhavrathi Could you please add the labels for this PR and for #23 and #24 also please?

**Pull request merged**
