### PR TITLE
Major changes 

### PR DESCRIPTION
**Pull request by ishita1818**
Now the user will be able to save the image, share the image (will add the share on facebook functionality later ..), have fixed the popping of keyboard, have set the font as impact( standard for memes), font color is white with a shadow of black (working on adding text size and color too), image editing is still in process but have created the required layout.
Update: I have added the text sizing and text color picker too.
 :)

meme1513338369281 1

Made this by using meme generator, background image is the screenshot of app in action during color picking.

### CODE REVIEW

**Comment by ishita1818** [comment]
@madhavrathi Could you please review the PR and let me know what else I can improve...

**Comment by madhavrathi** [comment]
@ishita1818 great work so far. Please resolve the conflicts. Thanks for your PR.

**Comment by ishita1818** [comment]
@madhavrathi 
Conflicts are happening because I have removed the top and bottom fragments, since we need to change the bitmap of original image and then save a copy of it. So, you can just delete them. For me, this resolve conflicts button is disabled so I am not able to do it.

**Comment by madhavrathi** [comment]
You can solve conflicts from command line too. Just do git pull --rebase and resolve conflicts and then do git rebase --continue
Let me know if there is any issue.
You can send me screenshots if any error occus on slack.
I assume you have setup origin remotes.

**Comment by ishita1818** [comment]
@madhavrathi  okay thanks! ... will let you know soon.

**Comment by ishita1818** [comment]
@madhavrathi I have removed the conflicts. Now you can review the changes. :)

**Comment by madhavrathi** [comment]
@ishita1818 Awesome. Thanks for your PR.

**Pull request merged**
