### PR TITLE
Change developer credentials

### LINKED ISSUE #4: Add export options for social media
Add export option for memes generated so that they can be published directly on Instagram, Facebook and other social platforms

### LINKED ISSUE #19: Make Facebook developer account for sdk use.
Would i like to work on it? Yes

### PR DESCRIPTION
**Pull request by Kartikdot**
Fixes #19 
Closes #4 
Added the developer credentials.
Id- nwoc.njack@gmail.com to be used for further api developer usage like obtaining tokens for the app etc.

### CODE REVIEW

**Review by madhavrathi — APPROVED** [review]
Thanks for your PR

**Review by madhavrathi — CHANGES_REQUESTED** [review]
Please resolve the conflicts.

**Comment by ShikharJ** [comment]
Ping @Kartik2016.

**Comment by Kartikdot** [comment]
I had resolved the conflicts. What needs to be done now?

**Comment by madhavrathi** [comment]
Conflicts are still there. Please check.

**Comment by Kartikdot** [comment]
Ok sure. I'll check it and resolve in a few minutes.

**Comment by Kartikdot** [comment]
Done!

**Comment by Kartikdot** [comment]
Is anything else required?

**Review by madhavrathi — APPROVED** [review]

**Pull request merged**
