### PR TITLE
Added draw on image in EditImage

### PR DESCRIPTION
**Pull request by ishita1818**
Now the user will be able to draw on the image.

1. 

screenshot_20171217-133405 1

2.

screenshot_20171217-133446 1

### CODE REVIEW

**Comment by ishita1818** [comment]
@madhavrathi Please review it.

**Review by madhavrathi — COMMENTED** [review]
Please resolve conflicts

**Comment by ishita1818** [comment]
@madhavrathi Done!

**Comment by madhavrathi** [comment]
Please resolve conflicts.

**Comment by ishita1818** [comment]
@madhavrathi I have resolved them yet again. Please review these.

**Review by madhavrathi — APPROVED** [review]

**Pull request merged**
